### ISSUE TITLE
fail to use with substrate-front-end-template: Cannot construct unknown type BlockWeights

### ISSUE THREAD

**Issue by askender** [kulupu/kulupu#118] opened 2021-01-28 16:18 UTC
index.js:1 2021-01-29        API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (Init.js:85)

we use https://github.com/substrate-developer-hub/substrate-front-end-template for basic dapp dev template.

help is needed. We need build dapp with kulupu or kulupu-based chain.
I searched a long time about the problem and cannot solve it.

**Comment by askender** [comment] 2021-01-28 16:19
@sorpaas   Can you take a look?   Thanks!!!

**Comment by MikeC-BC** [comment] 2021-02-22 16:58
Having this issue with the Polkadot Substrate API after initialing it with `yarn run main` 

```2021-02-22 16:55:15 error:         API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (/substrate-api/node_modules/@polkadot/api/base/Init.js:85:25)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)```

**Comment by sgaragagghu** [comment] 2021-03-13 13:08
It's working fine for me: kulupu 2.6.1 and frontend 3.0.0

**Comment by sorpaas** [comment] 2021-03-13 16:27
Caused by outdated polkadot-js version. Closing.

**Closed by sorpaas** 2021-03-13 16:27 UTC
