### ISSUE TITLE
Bug report - Node cannot mine any more

### ISSUE THREAD

**Issue by nidea4u** [kulupu/kulupu#1] opened 2019-09-22 02:19 UTC
<img width="548" alt="Screen Shot 2019-09-21 at 6 09 45 PM" src="https://user-images.githubusercontent.com/24986489/65381377-bfac5400-dca4-11e9-8901-06224bec194d.png">

**Comment by JoshOrndorff** [comment] 2019-10-21 21:41
Dupe of #3. This one is older, but that one is more thorough. Recommend closing this one.

**Closed** 2019-10-30 17:43 UTC
