### ISSUE TITLE
use js-sdk method getBlock error

### ISSUE THREAD

**Issue by Yangxin-GG** [kulupu/kulupu#115] opened 2020-12-31 04:47 UTC
Block in 334250 334252 334253 334254...."GetBlock " : Error: createType(SignedBlock):: Struct: failed on block: {"header":" header"," Extrinsics ":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Unable to create Enum via index 170, in Ed25519, Sr25519, Ecdsa

js version 2.10.1 and 3.2.1

**Comment by Yangxin-GG** [comment] 2020-12-31 04:48
![image](https://user-images.githubusercontent.com/30194654/103394912-5b926400-4b66-11eb-9933-66529743e58d.png)

**Comment by Yangxin-GG** [comment] 2020-12-31 04:49
Block in 334250 334252 334253 334254....

**Comment by sorpaas** [comment] 2021-03-13 16:27
Caused by outdated polkadot-js version. Closing.

**Closed by sorpaas** 2021-03-13 16:27 UTC
