### ISSUE TITLE
ERROR sc_consensus_pow  Mining block failed with Other("Unable to mine: fetch pair from author failed").

### ISSUE THREAD

**Issue by chovy** [kulupu/kulupu#74] opened 2020-08-30 18:54 UTC
`2020-08-30 18:53:10.878  ERROR sc_consensus_pow  Mining block failed with Other("Unable to mine: fetch pair from author failed"). Sleep for 1 second before restarting...`

getting this when running kulupu to mine

**Comment by sorpaas** [comment] 2020-08-30 20:22
Duplicate of https://github.com/kulupu/kulupu/issues/70

**Closed by sorpaas** 2020-08-30 20:22 UTC
