### ISSUE TITLE
Please fix miner. 2.4.0 lot of issues

### ISSUE THREAD

**Issue by Sepkuh** [kulupu/kulupu#121] opened 2021-02-04 18:47 UTC
Please fix miner. 2.4.0 doesn't work good. And I'm not talking about that core dump every 3 days, which is annoying too. My guess is a memory leak miner side (large pages related). Would be nice if fixed too. 

But the main problem is that hash suddely drops significantly and stays there.  After core dump it's ok again.  The version between 2.3.0 and 2.4.0 seems to work best.  This issue is addressed many times in #miner.  Could you look at it when you have time. Thanks.

**Comment by sorpaas** [comment] 2021-03-13 16:10
duplicate of #137

**Closed by sorpaas** 2021-03-13 16:10 UTC
